### ISSUE TITLE
📦 Item: Scientific Illustrations

### ISSUE THREAD

**Issue by emmyc** [emmyc/moving-on#22]
Features:
- Use the react-pageflip implementation seen in the `Yearbook` component to create a book for the illustrations.
- Cassette icon top right should play different song for each page.
- Add indicator for cassette icon on page flip to signify that a different song will play (not sure how you want to execute this, you could have a diff song title appear under the icon, or give it a different color)

![image](https://user-images.githubusercontent.com/17055138/119186109-7b9ac500-ba2c-11eb-9506-0dc5ebecba77.png)

**Comment by andersonxanna** [comment]
Added Fieldbook component
